CREATE TABLE IF NOT EXISTS parkovani (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  parkovaci_misto VARCHAR(10) NOT NULL,
  patro INT NOT NULL,
  zabrano BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS auto (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  parkovani_id INTEGER NOT NULL,
  SPZ VARCHAR(20),
  typ VARCHAR(20),
  majitel VARCHAR(50),
  barva VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS cas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  parkovani_id INTEGER NOT NULL,
  cas_zaparkovani DATETIME,
  cas_odjezdu DATETIME
);
